### ISSUE TITLE
240MHzの書き込み方について

### ISSUE THREAD

**Issue by atssada** [cliffgraph/CT-ARK#1]
まず、こういう素晴らしい作品を公開していただきありがとうございます。
こういう公開されているものをまねしながら楽しむことしか能のないものとして、非常に恥ずかしいですが、240MHz版のPicoへの書き込み方が別途存在するのでしょうか？
USBケーブルを差し込んで出てくるフォルダーにファイルを入れるだけでは機能せず、別クロック版は機能しているカートでした。
急ぎでもなんでもないので、お時間のある時にご説明いただけるだけでも結構ですのでよろしくお願いいたします。

**Comment by cliffgraph** [comment]
ありがとうございます！楽しんでいただけていることに、私も嬉しいです
240MHz版が動作しないこと、了解しました。すみません、仕事の都合ですぐには取りかかれないので、しばらくお待ち下さい。調査と改善できましたら、再度ここに書き込みます

**Comment by cliffgraph** [comment]
こんにちは、返信が遅れ申し訳ありません。240MHz版のPicoへの書き込み方法は125MHz版と同じです。こちらでも再度確認しましたが、240MHz版は正しく動作しました。私も多くのMSX本体で確認が取れていないので、MSX本体によっては相性が悪く動作しないのかもしれません。解決案が提示できず申し訳ありません。

**Comment by atssada** [comment]
ご親切にご説明いただきありがとうございます！個体の問題の可能性もあると思いますのでいくつか試してみます！ありがとうございます！

**Comment by atssada** [comment]
別のRaspberry Picoでうまくいきました！ありがとうございます！
